#!/usr/bin/env python3

import os
import argparse
import subprocess
from datetime import date


def new_proj(sc_dir, name, where, create_subdirs, create_config):
  # define template path
  src_dir   = os.path.join(sc_dir, "resources", "newproj_files")
  proj_dir  = os.path.join(where, name)
  
  # check if where is a valid path
  if not os.path.exists(where):
    raise ValueError(f"Error: The specified directory '{where}' does not exist.")
  if not os.path.isdir(where):
    raise ValueError(f"Error: '{where}' is not a directory.")

  # check if project already exists
  if os.path.exists(proj_dir):
    raise ValueError("project already exists")

  # create project directory
  os.mkdir(proj_dir)
  os.chdir(proj_dir)

  # create required directories
  dir_ls = ['.log', 'data', 'code', 'analysis', 'output', 'public']
  for d in dir_ls:
    os.mkdir(d)

  # create additional subdirectories if requested
  if create_subdirs:
    os.mkdir(os.path.join(proj_dir, 'data', 'fastqs'))
    os.mkdir(os.path.join(proj_dir, 'data', 'metadata'))
  
  # define required files and locations
  f_ls = ['_workflowr.yml', '.gitignore', '.gitattributes',
      '_site.yml', 'custom.css', 'about.Rmd', 'index.Rmd', 'license.Rmd', '.nojekyll']
  loc_ls = ['.', '.', '.', 'analysis', 'analysis', 'analysis', 'analysis', 'analysis', 'public']
  assert len(f_ls) == len(loc_ls)

  # copy template files
  for f, l in zip(f_ls, loc_ls):
    subprocess.call(['cp', os.path.join(src_dir, f), os.path.join(proj_dir, l, f)])

  # Modify _site.yml
  site_f = os.path.join(proj_dir, 'analysis', '_site.yml')
  with open(site_f, 'r') as file:
    site_yml_txt = file.read()
  site_yml_txt = site_yml_txt.replace("proj_template", name)
  with open(site_f, 'w') as file:
    file.write(site_yml_txt)

  # copy project file
  proj_ext = '.Rproj'
  subprocess.call(['cp', os.path.join(src_dir, "proj_template" + proj_ext), os.path.join(proj_dir, name + proj_ext)])
           
  # create .Rprofile file
  rprofile_txt = """## This makes sure that R loads the workflowr package
  ## automatically, every time the project is loaded
  if (requireNamespace("workflowr", quietly = TRUE)) {
    message("Loading .Rprofile for the current workflowr project")
    library("workflowr")
  } else {
    message("workflowr package not installed, please run install.packages(\'workflowr\') to use the workflowr functions")
  }
  """
  rprofile_f = os.path.join(proj_dir, '.Rprofile')
  with open(rprofile_f, "w") as file:
    file.write(rprofile_txt)

  # create config file if requested
  if create_config:
    config_f  = os.path.join(proj_dir, f"config_{name}.yaml")
    today     = date.today()
    date_stamp  = today.strftime('%Y-%m-%d')
    fastq_dir   = 'data/fastqs' if create_subdirs else ''
    meta_dir  = 'data/metadata' if create_subdirs else ''
    
    config_txt = f"""
proj_dir: {proj_dir}
fastq_dir: {fastq_dir}
full_tag: {name}
short_tag: 
your_name: 
affiliation: 
sample_metadata: {meta_dir}/
species: 
date_stamp: "{date_stamp}"
alevin:
 chemistry: 
""".strip()
    
    with open(config_f, "w") as file:
      file.write(config_txt)

  return



if __name__ == '__main__':
  sc_dir = os.path.dirname(os.path.realpath(__file__))

  # define arguments
  parser = argparse.ArgumentParser()
  parser.add_argument('name', type=str, help="Name of the project")
  parser.add_argument('-w', '--where', type=str, default=os.getcwd(), help="Where to create the project (default: current directory)")
  parser.add_argument('-s', '--sub', action='store_true', help="Create data/fastqs and data/metadata subdirectories")
  parser.add_argument('-c', '--config', action='store_true', help="Create a blank config.yml file with required scprocess parameters")
  
  # Get arguments
  args = parser.parse_args()
  where_abs = os.path.abspath(args.where)

  # Make new project directory
  new_proj(sc_dir, args.name, where_abs, args.sub, args.config)
