#!/usr/bin/env python3

import os
import argparse
import subprocess

# Little script to set up a new workflowr project
def new_proj(sc_dir, name, where):
    # Define template path
    cfg_dir = os.path.join(sc_dir, "proj_template")  # Get path to dir where all wflowr files are stored
    proj_dir = os.path.join(where, name)

    # Check doesn't already exist
    if os.path.exists(proj_dir):
        raise ValueError("Project already exists")

    # Create this directory, and move into it
    os.mkdir(proj_dir)
    os.chdir(proj_dir)

    # Create required directories
    dir_ls = ['.log', 'data', 'code', 'analysis', 'output', 'public']
    for d in dir_ls:
        os.mkdir(d)

    # Define required files and locations
    f_ls = ['_workflowr.yml', '.gitignore', '.gitattributes',
            '_site.yml', 'about.Rmd', 'index.Rmd', 'license.Rmd', '.nojekyll']
    loc_ls = ['.', '.', '.', 'analysis', 'analysis', 'analysis', 'analysis', 'public']
    assert len(f_ls) == len(loc_ls)

    # Copy these files to the correct locations
    for f, l in zip(f_ls, loc_ls):
        subprocess.call(['cp',
                         os.path.join(cfg_dir, f),
                         os.path.join(proj_dir, l, f)])

    # Modify _site.yml
    site_f = os.path.join(proj_dir, 'analysis', '_site.yml')
    with open(site_f, 'r') as file:
        site_yml_txt = file.read()
    site_yml_txt = site_yml_txt.replace("proj_template", name)
    with open(site_f, 'w') as file:
        file.write(site_yml_txt)

    # Copy project file
    proj_ext = '.Rproj'
    subprocess.call(['cp',
                     os.path.join(cfg_dir, "proj_template" + proj_ext),
                     os.path.join(proj_dir, name + proj_ext)])
                     
    # Create .Rprofile file
    rprofile_txt = """## This makes sure that R loads the workflowr package
    ## automatically, everytime the project is loaded
    if (requireNamespace("workflowr", quietly = TRUE)) {
      message("Loading .Rprofile for the current workflowr project")
      library("workflowr")
    } else {
      message("workflowr package not installed, please run install.packages(\\"workflowr\\") to use the workflowr functions")
    }
    """
    rprofile_f = os.path.join(proj_dir, '.Rprofile')

    with open(rprofile_f, "w") as file:
      file.write(rprofile_txt)

    return


# Set up arguments
if __name__ == '__main__':
    sc_dir = os.path.dirname(os.path.realpath(__file__))

    # Define arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('-n', '--name', type=str)
    parser.add_argument("-w", "--where", type=str)

    # Get arguments
    args = parser.parse_args()
    
    where_abs = os.path.abspath(args.where)

    # Make new project directory
    new_proj(sc_dir, args.name, where_abs)


