#!/usr/bin/env python3

# PATH="${PATH:+${PATH}:}/home/macnairw/packages/scProcess/scprocess.py"

# import utils
import argparse
import os
import sys
import textwrap
import yaml
import pathlib
import pandas as pd
import polars as pl
import glob
import subprocess
import shlex

# import scprocess functions
scprocess_dir  = os.path.dirname(__file__)
sys.path.append(os.path.join(scprocess_dir, 'scripts'))
import scprocess_utils


# scprocess setup
def run_setup(sc_dir, snakefile, extraargs):
  print('doing some checks on inputs')
 
  # get scprocess_data_dir; should be defined in .bashrc
  scprocess_data_dir = os.getenv('SCPROCESS_DATA_DIR')
  if scprocess_data_dir:
    print(f'SCPROCESS_DATA_DIR is set to: {scprocess_data_dir}')
  else:
    raise ValueError('SCPROCESS_DATA_DIR is not defined in .bashrc')
  
  # check that scprocess_data_dir is a directory
  if not os.path.isdir(scprocess_data_dir):
    raise FileNotFoundError("SCPROCESS_DATA_DIR is not a directory")
  
  # check that config file exists
  setup_config  = os.path.join(scprocess_data_dir, 'scprocess_setup.yaml')
  if not os.path.exists(setup_config):
    raise FileNotFoundError(f"Config file {setup_config} does not exist")
  
  # load config file  
  with open(setup_config, "r") as stream:
    config      = yaml.safe_load(stream)
  
  # check if cluster profile is defined
  if ('profile' in config) and config['profile'] is not None:    
    # check if profile exists
    profile     = config['profile']
    profile_dir = os.path.join(sc_dir, 'profiles', profile)
    profile_f   = os.path.join(profile_dir, 'config.yaml')
    if not os.path.isfile(profile_f):
      raise FileNotFoundError(f"cluster configuration file {profile_f} does not exist")
    
    # add snakemake flag
    extraargs = extraargs + ' --workflow-profile ' + profile_dir
    
  # change scprocess directory
  scprocess_dir  = os.path.dirname(__file__)
  os.chdir(scprocess_dir)

  # change scprocess directory
  print("starting scprocess setup")
  subprocess.run(['echo', 'snakemake', 
    "--snakefile", snakefile, 
    "--configfile", os.path.abspath(setup_config),
    "--rerun-triggers", "mtime", "params", "--rerun-incomplete", "--verbose", "--use-conda", 
    *shlex.split(extraargs)])
  subprocess.run(['snakemake', 
    "--snakefile", snakefile, 
    "--configfile", os.path.abspath(setup_config),
    "--rerun-triggers", "mtime", "params", "--rerun-incomplete", "--verbose", "--use-conda", 
    *shlex.split(extraargs)])


# scprocess newproj
def new_proj(sc_dir, name, where, create_subdirs, create_config):
  # define template path
  src_dir   = os.path.join(sc_dir, "resources", "newproj_files")
  proj_dir  = os.path.join(where, name)
  
  # check if where is a valid path
  if not os.path.exists(where):
    raise ValueError(f"Error: The specified directory '{where}' does not exist.")
  if not os.path.isdir(where):
    raise ValueError(f"Error: '{where}' is not a directory.")

  # check if project already exists
  if os.path.exists(proj_dir):
    raise ValueError("project already exists")

  # create project directory
  os.mkdir(proj_dir)
  os.chdir(proj_dir)

  # create required directories
  dir_ls = ['.log', 'data', 'code', 'analysis', 'output', 'public']
  for d in dir_ls:
    os.mkdir(d)

  # create additional subdirectories if requested
  if create_subdirs:
    os.mkdir(os.path.join(proj_dir, 'data', 'fastqs'))
    os.mkdir(os.path.join(proj_dir, 'data', 'metadata'))
  
  # define required files and locations
  f_ls = ['_workflowr.yml', '.gitignore', '.gitattributes',
      '_site.yml', 'custom.css', 'about.Rmd', 'index.Rmd', 'license.Rmd', '.nojekyll']
  loc_ls = ['.', '.', '.', 'analysis', 'analysis', 'analysis', 'analysis', 'analysis', 'public']
  assert len(f_ls) == len(loc_ls)

  # copy template files
  for f, l in zip(f_ls, loc_ls):
    subprocess.call(['cp', os.path.join(src_dir, f), os.path.join(proj_dir, l, f)])

  # Modify _site.yml
  site_f = os.path.join(proj_dir, 'analysis', '_site.yml')
  with open(site_f, 'r') as file:
    site_yml_txt = file.read()
  site_yml_txt = site_yml_txt.replace("proj_template", name)
  with open(site_f, 'w') as file:
    file.write(site_yml_txt)

  # copy project file
  proj_ext = '.Rproj'
  subprocess.call(['cp', os.path.join(src_dir, "proj_template" + proj_ext), os.path.join(proj_dir, name + proj_ext)])
           
  # create .Rprofile file
  rprofile_txt = """## This makes sure that R loads the workflowr package
  ## automatically, every time the project is loaded
  if (requireNamespace("workflowr", quietly = TRUE)) {
    message("Loading .Rprofile for the current workflowr project")
    library("workflowr")
  } else {
    message("workflowr package not installed, please run install.packages(\'workflowr\') to use the workflowr functions")
  }
  """
  rprofile_txt  = textwrap.dedent(rprofile_txt)
  rprofile_f    = os.path.join(proj_dir, '.Rprofile')
  with open(rprofile_f, "w") as file:
    file.write(rprofile_txt)

  # create config file if requested
  if create_config is not None:
    # import something we need
    from datetime import date

    # set up files etc
    config_f    = os.path.join(proj_dir, f"config-{name}.yaml")
    today       = date.today()
    date_stamp  = today.strftime('%Y-%m-%d')
    fastq_dir   = 'data/fastqs' if create_subdirs else ''
    meta_dir    = 'data/metadata' if create_subdirs else ''
    
    # define config text
    proj_txt    = f"""
      # for details on how to fill out the config file, please see the following link:
      # https://macnairw.pages.roche.com/scprocess/reference
      project:
        proj_dir: {proj_dir}
        fastq_dir: {fastq_dir}
        full_tag: {name}
        short_tag: 
        your_name: 
        affiliation: 
        sample_metadata: {meta_dir}/
        species: 
        date_stamp: "{date_stamp}"
        tenx_chemistry: 
      """
    if "sc" in create_config:
      qc_txt = """qc:
        qc_max_mito: 0.1
        qc_min_splice: 0.10
        qc_max_splice: 0.99
      """
    if "sn" in create_config:
      qc_txt = """qc:
        qc_max_mito: 0.1
        qc_max_splice: 0.75
      """
    if "multiplex" in create_config:
      multi_txt = """multiplexing:
        demux_type:
      """
    else:
      multi_txt = ""

    # join together
    config_txt  = proj_txt + multi_txt + qc_txt
    config_txt  = textwrap.dedent(config_txt).strip()
    
    # write to file
    with open(config_f, "w") as file:
      file.write(config_txt)

  return


# scprocess run
def run_scprocess(sc_dir, configfile, snakefile, rule, extraargs, noindex):
  print('doing some checks on inputs')

  # housekeeping
  config_path     = pathlib.Path(configfile).resolve()
  scprocess_dir   = pathlib.Path(__file__).parent
  os.chdir(scprocess_dir)

  # do some checks
  scdata_dir, extraargs = scprocess_utils.check_setup_before_running_scprocess(scprocess_dir, extraargs)

  # get validated config
  with open(config_path, "r") as f:
    config          = yaml.safe_load(f)
  schema_f        = scprocess_dir / "resources/schemas/config.schema.json"
  if not schema_f.is_file():
    raise FileNotFoundError("schema file not found")
  config          = scprocess_utils.check_config(config, schema_f, scdata_dir, scprocess_dir)

  # get lists of parameters
  RUN_PARAMS, RUN_VAR     = scprocess_utils.get_run_parameters(config, scdata_dir)
  RUNS                    = list(RUN_PARAMS.keys())
  BATCH_PARAMS, BATCH_VAR = scprocess_utils.get_batch_parameters(config, RUNS, scdata_dir)
  BATCHES                 = list(BATCH_PARAMS.keys())
  BATCHES_TO_RUNS         = scprocess_utils.get_batches_to_runs(config, RUNS, BATCHES, BATCH_VAR)

  # print which files will be processed
  print(f"\nprocessing {len(BATCHES)} samples:")
  print('  ' + ', '.join(BATCHES))

  # print out what we will do:
  print("\nsnakemake command:")
  subprocess.run(["echo", "snakemake", 
    "--snakefile", snakefile, 
    "--configfile", config_path,
    "--config", f"scprocess_dir={str(scprocess_dir)}",
    "--rerun-triggers", "mtime", "params", "--rerun-incomplete", "--verbose", 
    "--software-deployment-method", "conda",
    "--use-apptainer", "--apptainer-args", f"--cleanenv --nv --bind /tmp,{config['project']['proj_dir']}",
    *shlex.split(extraargs),
    rule
    ])
  # do it
  subprocess.run(["snakemake", 
    "--snakefile", snakefile, 
    "--configfile", config_path,
    "--config", f"scprocess_dir={str(scprocess_dir)}",
    "--rerun-triggers", "mtime", "params", "--rerun-incomplete", "--verbose", 
    "--software-deployment-method", "conda",
    "--use-apptainer", "--apptainer-args", f"--cleanenv --nv --bind /tmp,{config['project']['proj_dir']}",
    *shlex.split(extraargs),
    rule
    ])
  if not noindex and " -np" not in extraargs:
    print("\nRendering index")
    subprocess.run(["snakemake", 
      "--snakefile", os.path.join(scprocess_dir, 'rules/scprocess.smk'), 
      "--configfile", config_path,
      "--config", f"scprocess_dir={str(scprocess_dir)}",
      "--software-deployment-method", "conda",
      "--rerun-triggers", "mtime",
      "--forcerun",
      *shlex.split(extraargs),
      "index"
      ],
      stdout=subprocess.DEVNULL,
      stderr=subprocess.DEVNULL  
    )
 
  return


# scprocess plotknee
def plot_interactive_knee(config_f, knee_f, sample):
  # check we can find the file
  if args.kneefile:
    knee_f      = pathlib.Path(args.kneefile)
    if not knee_f.is_file():
      raise FileNotFoundError(f"Specified knee file doesn't exist. Check for typos, but", 
        " if the file doesn't exist you can generate the file by running the rule 'mapping'")
  else:
    # open config file and get project directory
    with open(config_f) as f:
      config = yaml.load(f, Loader=yaml.FullLoader)
    
    # get required variables
    proj_dir    = pathlib.Path(config['project']['proj_dir'])
    short_tag   = config['project']['short_tag']
    date_stamp  = config['project']['date_stamp']

    # use them to define a knee file to use
    knee_f      = proj_dir / f"output/{short_tag}_mapping/af_{sample}" / f"knee_plot_data_{sample}_{date_stamp}.txt.gz"
    if not knee_f.is_file():
      knee_f      = proj_dir / f"output/{short_tag}_mapping/af_{sample}/rna" / f"knee_plot_data_{sample}_{date_stamp}.txt.gz"
    if not knee_f.is_file():
      raise FileNotFoundError(f"Knee file for {sample} doesn't exist. You can generate it ", 
        "by running the rule 'mapping'")

  print('importing modules for plotting knees')
  import gzip
  import plotly.express as px
  from plotly.offline import plot

  # read knee file
  knee_df = pl.read_csv(knee_f)

  # make plot
  fig = px.scatter(
    knee_df.to_pandas(),
    x='rank',
    y='total',
    title=f"sample_id: {sample}",
    log_x=True, 
    log_y=True, 
    labels={'rank': 'barcode rank', 'total': 'library size'}
  )
  fig.update_traces(marker=dict(color='black', size=5))

  # update the layout to set background colors
  fig.update_layout(
    plot_bgcolor  = 'white', 
    paper_bgcolor = 'white',
    xaxis     = dict( gridcolor = '#e5e7e9', zerolinecolor = '#e5e7e9' ),
    yaxis     = dict( gridcolor = '#e5e7e9', zerolinecolor = '#e5e7e9' ),
    autosize  = False,
    width     = 1200,
    height    = 700
  )

  # save plot as html file
  knee_dir  = os.path.dirname(knee_f)
  plot_f    = os.path.join(knee_dir, f"scprocess_knee_plot_{sample}.html")
  fig.write_html(plot_f)
  # plot(fig, auto_open=True)

  # tell user where knee plot was saved
  print(f"interactive knee plot saved here:\n  {plot_f}")


if __name__ == '__main__':
  # define arguments
  parser      = argparse.ArgumentParser(
    description = 'snakemake workflows for processing single cell RNAseq data.'
  )
  subparsers  = parser.add_subparsers(dest='subcommand', help="scprocess subcommands:", required=True)

  # subparser for the 'setup' subcommand
  setup_prsr  = subparsers.add_parser('setup', help="do setup for scprocess")

  # add arguments for setup
  setup_prsr.add_argument("-n", "--dry-run", action="store_true", 
    help = '''
      "Dry run" execution, i.e. snakemake will print out what it would do for the setup step, but not actually do it.
      ''')
  setup_prsr.add_argument("-E", "--extraargs", action="store", nargs=1, type=str,
    help = '''
      Extra snakamake arguments. Must be provided within quotes and use an equals sign.
      For example, to have a dryrun: -E="-n"
      ''')

  # subparser for the 'plotknee' subcommand
  newprj_prsr = subparsers.add_parser('newproj', help="create new project folder with structure that scprocess expects")

  # add arguments for new project
  newprj_prsr.add_argument('name', type=str, help="Name of the project")
  newprj_prsr.add_argument('-w', '--where', type=str, default=os.getcwd(), help="Where to create the project (default: current directory)")
  newprj_prsr.add_argument('-s', '--sub', action='store_true', help="Create data/fastqs and data/metadata subdirectories")
  newprj_prsr.add_argument('-c', '--config', type=str, choices = ["sc", "sn", "multiplex"], nargs="+",
    help="Create a blank config.yml file with required scprocess parameters. Users must specify at least one option from: sc (single cell); sn (single nuclei); multiplex.")

  # subparser for the 'run' subcommand
  run_prsr    = subparsers.add_parser('run', help="run scprocess")

  # add arguments for scprocess
  run_prsr.add_argument("configfile", type = str, 
    help = "Required. YAML file specifying what you want to run, and any non-default parameters")
  run_prsr.add_argument("-r", "--rule", type = str, default = "all",
    choices = [
        "all", "mapping", "ambient", "demux", "qc", "hvg", "integration", "marker_genes", "label_celltypes", "zoom"
        ],
    help = '''
      Leave empty to run the whole workflow, or alternatively select the rule you want to run.
      ''')
  run_prsr.add_argument("-n", "--dry-run", action="store_true", 
    help = '''
      "Dry run" execution, i.e. snakemake will print out what it would do, but not actually do it.
      ''')
  run_prsr.add_argument("-E", "--extraargs", type = str, 
    help = '''
      Extra snakamake arguments. Must be provided within quotes. For example, to reduce outputs from snakemake: -E "--quiet"
      ''')
  run_prsr.add_argument("--unlock", action="store_true", 
    help = '''
      When an scprocess run is stopped before it is finished, the snakemake directory
      may be locked. If you get an error message saying that it is locked, use this
      option to unlock it, then run scprocess as normal.
      ''')
  run_prsr.add_argument("--noindex", action='store_true', 
    help = "")

  # subparser for the 'plotknee' subcommand
  knee_parser = subparsers.add_parser('plotknee', help="save interactive knee plot for a specified sample, to help specify custom parameters")

  # define arguments
  knee_parser.add_argument("sample", type = str, help = 'Sample to be plotted.')
  group       = knee_parser.add_mutually_exclusive_group()
  group.add_argument("-c", "--configfile", type = str, nargs = '?', default = None,
    help = "Path to configuration file used for running scprocess. ")
  group.add_argument("-k", "--kneefile", type = str, default = None,
    help = "Path to knee file")

  # define scprocess directory
  sc_dir    = os.path.dirname(os.path.realpath(__file__))

  # Parse the arguments
  args      = parser.parse_args()
  
  # create new project folder
  if args.subcommand == "setup":
    # select snakefile corresponding to workflow
    snakefile = os.path.join(sc_dir, "rules/setup.smk")

    # sort out extra arguments
    extraargs = ' '
    if args.extraargs:
      extraargs = extraargs + args.extraargs[0]
    if args.dry_run:
      extraargs = extraargs + " -np"
    
    # call bsub thing
    run_setup(sc_dir, snakefile, extraargs)

  elif args.subcommand == "newproj":
    # make new project directory
    if ('sc' in args.config) and ('sn' in args.config):
      raise ValueError("When specifying --config / -c, only one of sc and sn can be specified at a time.")
    where_abs = os.path.abspath(args.where)
    new_proj(sc_dir, args.name, where_abs, args.sub, args.config)

  # run scprocess
  elif args.subcommand == "run":
    # set default rule to all
    if args.rule == "":
      rule    = "all"
    else:
      rule = args.rule  
    
    # select snakefile corresponding to workflow
    if rule == "zoom":
      snakefile = os.path.join(sc_dir, "rules/zoom.smk")
    else:
      snakefile = os.path.join(sc_dir, "rules/scprocess.smk")

    # sort out extra arguments
    extraargs = ' '
    noindex   = args.noindex
    if args.unlock:
      extraargs = " --unlock"
      noindex   = True
    else:
      if args.extraargs:
        extraargs = extraargs + args.extraargs
      if args.dry_run:
        extraargs = extraargs + " -np"
        noindex   = True
    
    # print(sc_dir, args.configfile, snakefile, rule)   
    # call bsub thing
    run_scprocess(sc_dir, args.configfile, snakefile, rule, extraargs, noindex)
  
  # plot knee for selected sample
  elif args.subcommand == 'plotknee':
    # call function
    plot_interactive_knee(args.configfile, args.kneefile, args.sample)

  else:
    # if no arguments are provided at all, print the help message
    parser.print_help()


