#!/usr/bin/env python3

import argparse
import os
import yaml
import pandas as pd
import re
import glob
import subprocess
import shlex


def run_scsetup(sc_dir, snakefile, extraargs):
  print('doing some checks on inputs')
 
  # get scprocess_data_dir; should be defined in .bashrc
  scprocess_data_dir = os.getenv('SCPROCESS_DATA_DIR')

  if scprocess_data_dir:
    print(f'SCPROCESS_DATA_DIR it set to: {scprocess_data_dir}')
  else:
    raise ValueError('SCPROCESS_DATA_DIR is not defined in .bashrc')
  
  # check that scprocess_data_dir is a directory
  assert os.path.isdir(scprocess_data_dir), \
   "SCPROCESS_DATA_DIR is not a directory"
  
  # check that config file exists
  configfile = os.path.join(scprocess_data_dir, 'scprocess_setup.yaml')
  assert os.path.exists(configfile), \
    f"Config file {configfile} does not exist"
  
  with open(configfile, "r") as stream:
    config      = yaml.safe_load(stream)
  
  # check if cluster profile is defined
  if ('profile' in config) and config['profile'] is not None:
    profile = config['profile']
    
    # check if profile exists
    profile_dir = os.path.join(sc_dir, 'profiles', profile)
    profile_f   = os.path.join(profile_dir, 'config.yaml')

    assert os.path.isfile(profile_f), \
      f"cluster configuration file {profile_f} does not exist"
    
    # add snakemake flag
    extraargs = extraargs + ' --workflow-profile ' + profile_dir
    
  # change scprocess directory
  scprocess_dir  = os.path.dirname(__file__)
  os.chdir(scprocess_dir)

  # change scprocess directory
  print("starting scprocess setup")
  subprocess.run(['echo', 'snakemake', 
    "--snakefile", snakefile, 
    "--configfile", os.path.abspath(configfile),
    "--rerun-triggers", "mtime", "--rerun-incomplete", "--verbose", "--use-conda", 
    *shlex.split(extraargs)])
  subprocess.run(['snakemake', 
    "--snakefile", snakefile, 
    "--configfile", os.path.abspath(configfile),
    "--rerun-triggers", "mtime", "--rerun-incomplete", "--verbose", "--use-conda", 
    *shlex.split(extraargs)])


if __name__ == '__main__':
  # define scprocess directory
  sc_dir    = os.path.dirname(os.path.realpath(__file__))

  # define arguments
  parser    = argparse.ArgumentParser( description = '''
    setup for scprocess: a snakemake workflow for processing single cell RNAseq data.
    ''')
  parser.add_argument("-n", "--dry-run", action="store_true", 
    help = '''
      "dry run" execution, i.e. snakemake will print out what it would do, but not actually do it.
      ''')
  parser.add_argument("-E", "--extraargs", action="store", nargs=1, type=str,
    help = '''
      extra snakamake arguments. Must be provided within quotes and use an equals sing.
      For example, to have a dryrun: -E="-n"
      ''')
       
  # get arguments
  args      = parser.parse_args()

  # select snakefile corresponding to workflow
  snakefile = os.path.join(sc_dir, "rules/setup_rules.smk")

  # sort out extra arguments
  extraargs = ''
  if args.extraargs:
    extraargs = args.extraargs[0]
  if args.dry_run:
    extraargs = extraargs + " -np"
  
  # call bsub thing
  run_scsetup(sc_dir, snakefile, extraargs)

